import { ApiResponse } from './apiResponse';

export interface LoginParams {
  user: string;
  pass: string;
}

// Generated by https://quicktype.io

export interface LoginResponse extends ApiResponse<LoginData> {}

export interface LoginData {
  token: string;
  level: string;
  nama: string;
  photo: string;
  lokasi: string;
}

export interface RegisterParams {
  nama: string;
  email: string;
  pass: string;
  repass: string;
}

export interface RegisterResponse extends ApiResponse<RegisterData> {}

export interface RegisterData {
  email: string;
}
