// Generated by https://quicktype.io

import { APIResponsePaginated } from './apiResponse';
import { ApiResponse } from './apiResponseTypes';

export interface WakafListParams {
  search?: string;
  start?: number;
  length?: number;
}

export interface WakafListResponse extends APIResponsePaginated<Wakaf> {}

export interface DetailWakafParams {
  id_wakaf: string;
}

export interface DetailWakafResponse
  extends ApiResponse<DetailWakafData | undefined> {}

export interface DetailWakafData {
  ID_WAKAF: string;
  KODE_LOKASI: string;
  KEL: string;
  KEC: string;
  KAB: string;
  PROV: string;
  KODE_PENG: string;
  PENGGUNAAN: string;
  NAMA: string;
  ALAMAT: string;
  WAKIF: string;
  NADZIR: string;
  LUAS: string;
  NO_AIW: string;
  TGL_AIW: string;
  NO_SERT: string;
  TGL_SERT: string;
  KET_PENG: string;
  KETERANGAN: string;
  ID_SW: string;
  JENIS_SW: string;
  ID_SP: string;
  JENIS_SP: string;
  ID_ST: string;
  JENIS_ST: string;
  ISDEL: string;
  ID_USER: string;
  ISOK: string;
  LAT: string;
  LNG: string;
  ICON: string;
  NILAI: string;
  JML_GAMBAR: string;
  NAMA_USER: string;
  ID_PS: string;
  PROSES: string;
  NO_BERKAS: string;
  ID_KRITERIA: string;
  KRITERIA: string;
  NIA: string;
}

export interface Wakaf {
  no: number;
  DT_RowId: string;
  no_aiw: string;
  no_sert: string;
  wakif: string;
  alamat: string;
  nilai: string;
  lat: string;
  lng: string;
  gambar: string;
  flag: string;
}

type DateParams = `${number}-${number}-${number}`;

export interface AddWakafParams {
  no_berkas?: string;
  no_aiw?: string;
  tgl_aiw?: DateParams;
  no_sert?: string;
  tgl_sert?: DateParams;
  alamat: string;
  prov: string;
  kab: string;
  kec: string;
  kel: string;
  nama?: string;
  wakif: string;
  nadzir: string;
  luas?: number;
  guna?: string;
  stanah?: string;
  sprod?: string;
  swakaf?: string;
  ket: string;
  lat: string;
  lng: string;
}

export interface AddWakafResponseData {
  id: number;
  token: string;
  no: string;
}

export interface AddWakafResponse extends ApiResponse<AddWakafResponseData> {}

export interface WakafListPictureParams {
  id_wakaf: string;
  jenis: WakafPictureType;
}

export enum WakafPictureType {
  CERTIFICATE = 1,
  AIW,
  PHYSICAL,
}

export interface WakafListPictureResponse
  extends ApiResponse<WakafListPictureData> {}

type WakafListPictureData = WakafPicture[];

// Generated by https://quicktype.io

export interface WakafPicture {
  id: string;
  path: string;
  fullpath: string;
  ket: string;
}

export interface AddWakafPictureParams {
  id: string;
  jenis: string;
  ket?: string;
  img: string;
}

export interface AddWakafPictureResponse {
  id: number;
  msg: string;
}

export interface UpdateWakafPictureParams {
  idm: string;
  jenis: string;
  ket?: string;
}

export interface UpdateWakafPictureResponse extends AddWakafPictureResponse {}

export interface DeleteWakafPictureParams {
  id_gambar: string;
}

export interface DeleteWakafPictureResponse extends AddWakafPictureResponse {}
